version: '3'

services:
  server:
    build:
      context: ./server
      args:
        UID: ${UID}
        GID: ${GID}
        SERVER_ROOT_PASSWORD: ${SERVER_ROOT_PASSWORD}
    container_name: server
    ports:
      - 80:80
      - "2200:22"
    volumes:
      - ./data/www:/home/serveruser/vhosts
    links:
      - db
    depends_on:
      - db
    extra_hosts:
      - "wwww.laranerds.local:127.0.0.1"
      - "laranerds.local:127.0.0.1"
    networks:
      app_net:
        ipv4_address: 10.100.100.11
  db:
    image: mariadb
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      app_net:
        ipv4_address: 10.100.100.21
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.100.100.0/24
volumes:
  db-data: